import Control.Exception

-- handle :: Exception e => (e -> IO a) -> IO a -> IO a
--
